### ISSUE TITLE
Temperatura de confort

### ISSUE THREAD

**Issue by agrauHCB** [carduque/FeerBoxClient#10]
Iniciar el tema de temperatura de confort amb temperatura i humitat relativa (els mercats ho estan demandant)

Mirar e-mail del Daniel on explica on es calcula la temperatura de comfort.

**Comment by agrauHCB** [comment]
Hauriem en la mesura del possible disposar del càlcul de la temperatura de confort

**Comment by carduque** [comment]
proposeu gràfic per la temperatura de confort. Quin tipus de gràfic seria?

**Comment by carduque** [comment]
This issue was moved to carduque/heroku#14
