### ISSUE TITLE
Complir Llei OLPD

### ISSUE THREAD

**Issue by agrauHCB** [carduque/FeerBoxClient#15]
Hem de saber el que hem de fer per complir amb la OLPD, guardem material sensible, i hem de saber que hem de fer

**Comment by carduque** [comment]
Això no es software... tampoc ens passem obrint tickets.

**Comment by agrauHCB** [comment]
Ok, no es software, és un Help wanted :)

**Comment by carduque** [comment]
This issue was moved to carduque/heroku#17
