### ISSUE TITLE
Configurar-ho wifi quan es necessita acceptar condicions via web

### ISSUE THREAD

**Issue by agrauHCB** [carduque/FeerBoxClient#17]
Hola,

Al Aki han demanat un dispositiu, i tenim el compta-persones, i potser hi haurà llocs que es necessita, seria genial investigar de com poder-ho fer.

**Comment by carduque** [comment]
Es pot fer de dos maneres:
1. Conectar pantalla i teclat temporal
2. Descarregar la plana que demana "acceptar les condicions": codi font + js files amb el mòvil o portatil. Fer investigació per crear script que cridi al submit del form per linea de commandes

**Comment by carduque** [comment]
This issue was moved to carduque/heroku#18
