### ISSUE TITLE
Formes connexió sensors

### ISSUE THREAD

**Issue by 4dan** [carduque/FeerBoxClient#2]
Formes connexió sensors:
Tuto Onrom pàg. 41 moltes de les diferents formes de connectar i alimentar un sensor, amb esquemes de 2 fils a relé, 3 fils, 4 fils...:
https://es.slideshare.net/IvanRocanlover281107/sensores-15345193

Per connectar els retroreflectors xinesos amb 5 cables amb sortida de relé:
![imatge](https://user-images.githubusercontent.com/32014087/31578193-8fefd71a-b11c-11e7-9d7c-41b316603354.png)

Un relé no te polaritat:
http://www.forosdeelectronica.com/f27/polaridades-rele-53609/

Un relé ès un circuit

**Comment by carduque** [comment]
wronly added as a issue

**Comment by 4dan** [comment]
Hoola Cales!

He rebut això i no entenc que vol dir?


2018-01-09 22:14 GMT+01:00 carduque <notifications@github.com>:
