### ISSUE TITLE
Incongruència

### ISSUE THREAD

**Issue by agrauHCB** [carduque/FeerBoxClient#20]
Hola,

A la botonera de Rubi 2017010 tenim una incongruència, si mirem el event 303 desde Analysis
http://dashboard.feerbox.com/answer/by_event?eventId=303
Surten unicament 29 respostes

Mentre que si ho mirem per on toca per View Reports surten 3830 respostes, 
http://dashboard.feerbox.com/report/display?id=149

Pots mirar que està passant?

Moltes Gràcies !

**Comment by carduque** [comment]
El Analysis utilitza el event 303 i el report el event 305, que les dates son iguales però un te el dispositiu 2017010 i l'altre 2017020.

**Comment by agrauHCB** [comment]
Correcte, hi havia d'haver una explicació.
Bona feina.

Haurem de suprimir aviat el Analytics, o deixar-ho com a consulta.
Així com fer neteja dels events.
