### ISSUE TITLE
Asignar al David Otero github

### ISSUE THREAD

**Issue by agrauHCB** [carduque/FeerBoxClient#26]
Hola Carles,

Dues coses:

 -1 Asignar al usuari de github doterog , en David Otero perque ser agregat al equip de gitub
- 2 Ha fet una app de conta persones per poder validar la eficacia, estaria bé que el codi el puges al nostre repositori, si li pots donar les indicacions

Moltes Gràcies

**Comment by carduque** [comment]
done. Pot pujar ja codi a:
https://github.com/carduque/CounterPeopleValidation.git

**Comment by agrauHCB** [comment]
Colta, no veig el David al desplegable de github quan assigno una issue

**Comment by carduque** [comment]
Ha d'acceptar la meva solicitut.
