### ISSUE TITLE
Bug en export de moltes dades en excel

### ISSUE THREAD

**Issue by agrauHCB** [carduque/FeerBoxClient#27]
Hola Carles,

Necessitem si pots passar directament de la base de dades la següent informació per a que el Quim prepari el informe per Joan del Mercat de la Independència.

Un excel per cada porta:
CP2017001 Porta Raval desde Setembre 2017 Fins 9 de Febrer 2018
CP2017002 Porta Rambla desde Setembre 2017 Fins 9 de Febrer 2018
CP2017003 Porta Raval desde Setembre 2017 Fins 9 de Febrer 2018
CP2017004 Porta Peix TENIM UN PROBLEMA DE SINCRONITZACIÓ !!!
CP2017006 Porta Ferran TENIM UN PROBLEMA DE SINCRONITZACIÓ !!!
2017008 Porta Rambla Rambla Desde 1 Desembre 2017 fins 9 de Febrer 2018
CP2017013 Porta Fupar Desde 1 Desembre 2017 fins 9 de Febrer 2018

Per les dues portes comprem 2 Huaweis, i dues targetes simyo més i aconseguim la sincronització, sino miro de baixar-me el fitxers.

Aquí s'ha de fer un estudi per cada porta.

**Comment by carduque** [comment]
Perque no utilitzeu l'export?

**Comment by agrauHCB** [comment]
No hem funciona, peta el excel, error 500

Com q no hi ha dades?

**Comment by carduque** [comment]
Però si no hi han ni els events!
jo he creat un event de la primera porta i va be (Event: Raval CDM)

**Comment by agrauHCB** [comment]
Hola,

He creat els events per les portes, m'ha fallat al descargar-me aquest event
http://dashboard.feerbox.com/counterpeople/excel?eventId=323

Els events son MerIndp.  + el nom de la porta

Thanks

**Comment by carduque** [comment]
Process running mem=532M(103.6%)
2018-02-18T18:18:10.020726+00:00 heroku[web.1]: Error R14 (Memory quota exceeded)

Els altres van be?

**Comment by carduque** [comment]
Intenta generar un excel de quasi 600.000 files, potser no és la millor manera.
Jo de moment partiria l'event en dos. Caldrà veure altres maneres d'exportar dades.

**Comment by agrauHCB** [comment]
ok, bona idea, no ho havia pensat !
