### ISSUE TITLE
Falla Report Mercat Independència

### ISSUE THREAD

**Issue by agrauHCB** [carduque/FeerBoxClient#28]
Hola Carles,

Si vas al View Report del Mercat de la Independència
http://dashboard.feerbox.com/report/display?id=152

Hauria de tenir dades desde Maig a Febrer, i surten dades nomes de desembre, gener i febrer

Thanks,
un saludo,

**Comment by carduque** [comment]
El gràfic "per dia", està limitat als últims dos mesos, la resta son de tot el periode.
No te sentit un report amb 200 gràfics.

**Comment by agrauHCB** [comment]
No hem refereixo al gràfic per dies, sino al gràfic per setmanes i mesos.
Ara he creat event només amb mesos i setmanes
Veig que els mesos de Gener 18 i Febrer18 Apareixen al inici enlloc de al Final, no es té en compte el any , m'explico?
http://dashboard.feerbox.com/report/display?id=153

**Comment by carduque** [comment]
Pero surten o no surten les dades? No te res a veure això últim amb el principi del ticket, no?

**Comment by agrauHCB** [comment]
El problema es que si es selecciona el tipo de gràfic per hores per dia a diari, llavors els gràfics de mesos i setmanes només agafa els 2 mesos, m'explico?
No hauria de passar, el que si que estic d'acord que per dia tingui un limit, pero que no afecti a la resta de gràfics, si?

Altra cosa es tb el tema de no tenir en compte el mes/any, ja que només es te en compte mes al gener els gràfics per mesos, si?

**Comment by carduque** [comment]
Per quan fa falta això?

**Comment by carduque** [comment]
Ara?

**Comment by agrauHCB** [comment]
A veure, aquesta issue es per la màquina de satisfacció del mercat de la independència, si pots endreçar les weeks i mesos tenint en compte el any

Per mi és important, sino no podem entregar el informe de satisfacció, i de fet, tb arreglarem Mercat de Rubí al fer el canvi d'any

**Comment by carduque** [comment]
http://dashboard.feerbox.com/report/display?id=153

**Comment by carduque** [comment]
This issue was moved to carduque/heroku#21
