### ISSUE TITLE
Entendre el concepte d'status de la raspi envia

### ISSUE THREAD

**Issue by agrauHCB** [carduque/FeerBoxClient#29]
Hola Carles,

M'agradaria entendre els camps que enviem amb el status report, bàsicament hi han que em preocupa
Ara som 18/02/18 a les 17:50, entre d'altres no entenc el CommandQueue.

Et puc proposar una canvis, és que el status és molt important.

Els status que envia
INTERNET = true
CommandQueue = 19/02/2018 03:01:12.423
IP = 192.168.1.38
PendingAnswersToUpload = 0
CommandExecutor = true
CPU = 25.2097%
MemoryProcess = 6.8%
SYSTEM_TIME = 18/02/2018 17:46:12.981
LAST_ANSWER =
FreeMemory = 84
JavaMemory = 23363584 - 4679992 - 235274240
TIME_UP = 0d - 17h - 46m
AverageUptime =

**Comment by carduque** [comment]
Proposa canvi.
CommandQueue es l'instant de temps següent en que demanarà un Command per executar al dashboard.

**Comment by carduque** [comment]
This issue was moved to carduque/heroku#22
