### ISSUE TITLE
Millora de botonera amb PIR

### ISSUE THREAD

**Issue by agrauHCB** [carduque/FeerBoxClient#30]
Hola 

Una millora que m'agradaria fer, es tenim botoneres amb PIR, quan detecti que hi ha una persona aprop s'iluminessin uns LED per cridar l'atenció del visitant i pitgi el botó.

Penso que es una millora interessant a nivell de funcionalitat, i tampoc hauria de ser massa/massa complicada

Thanks !

**Comment by carduque** [comment]
This issue was moved to carduque/heroku#23
