### ISSUE TITLE
Certificacions/Homologacions Botonera

### ISSUE THREAD

**Issue by agrauHCB** [carduque/FeerBoxClient#31]
El passat divendres, vam fer una reunió amb Lluis Fusté, expert en homologacions

Va dir coses interessant de cara a la certificació i que tinguem el logo CE al nostre producte.

Hem de tenir els datasheets de tots els productes.

**Comment by agrauHCB** [comment]
Sobretot, és feina pel Dani que hem d'aconseguir tots els datasheets dels fabricants, ho treballaré amb ell.

**Comment by carduque** [comment]
This issue was moved to carduque/heroku#24
