### ISSUE TITLE
Comprar botons anti-vandàlics

### ISSUE THREAD

**Issue by agrauHCB** [carduque/FeerBoxClient#32]
Pots passar-me els botons antivandàlics, m'agradaria tenir-ne 3 botons per fer una prova.

Tenim reunió amb empresa de neteja que posen banys sense vigilància, potser seria una bona idea.

Passa'm enllaç, ho poso high priority perque només es passar-me enllaç i ho tanquem aquesta issue

Thanks

Albert Grau

**Comment by carduque** [comment]
Jo he trobat aquest. El Daniel ha de validar si serveix o no
https://www.electronicaembajadores.com/es/Productos/Detalle/IT4A008/interruptores-conmutadores-pulsadores/pulsadores-de-panel/pulsador-panel-1na-antivandalico

**Comment by agrauHCB** [comment]
Perfecte, gràcies !

**Comment by agrauHCB** [comment]
comprats

**Comment by agrauHCB** [comment]
Epps, cagada
El botons són molt petits, en pots buscar de més grans, son xulos, la veritat que queden bé, pero han de ser com el doble o triple de gran.

Ara ja tenim una referència.

**Comment by carduque** [comment]
Jo no he trobat i diria que no existeix, una mica per definició

**Comment by agrauHCB** [comment]
Ja en busco, això com els iogurts, hemos de seguir buscando :)

**Comment by carduque** [comment]
This issue was moved to carduque/heroku#25
