### ISSUE TITLE
Caixes CTB 

### ISSUE THREAD

**Issue by agrauHCB** [carduque/FeerBoxClient#33]
Mides de la caixa, es dedicar-hi una estona, si trobes algo, i tanca'l.

et passo la mides mínimes per la CTB per trobar una nova caixa més reduïda.
mides:  18 x 23 x 6,5 cm
Si fem servir botons de perfil més baix:
Polsador Il·luminat  28mm diàmetre de forat, de 5 v LED Push Button
Profunditat 33mm 0,9€:
https://es.aliexpress.com/item/illuminated-28-mm-hole-diametre-5-v-LED-Arcade-Push-Button-with-microswitch-for-KOF/32790575812.html?spm=a219c.10010108.1000014.22.1c974bb2xNNAV8&traffic_analysisId=recommend_3035_11_83054_iswinstore&scm=1007.13338.83054.0&pvid=d431b1f3-e103-43d4-9986-96c1e2dac477&tpp=1

**Comment by carduque** [comment]
No tinc temps per buscar caixes

**Comment by agrauHCB** [comment]
ok, cap problema

**Comment by agrauHCB** [comment]
Estem fent de fusta, de moment, feta pel meu pare.

**Comment by carduque** [comment]
This issue was moved to carduque/heroku#26
