### ISSUE TITLE
Problema amb els sensors.

### ISSUE THREAD

**Issue by doterog** [carduque/FeerBoxClient#34]
Estic fent la validació dels sensors del Marcat de la Independència amb els valors que vam recollir ahir el Daniel i jo.
El problema és que els sensors instal·lats detecten menys persones de les que realment han passat, cosa que esperàvem que fos el reves. El cas mes alarmant és la porta de la Raval, on les persones comptabilitzades varen ser un total de 122 persones entre les 11:49:00 i les 12:16:53. Mentre que els sensors només van agafar 68 persones entre les 11:48:46.125 i 12:17:39.020.
Parlant amb l'Albert hem cregut que els valors, en tot cas haurien de ser el contrari, per tant creiem que es tracte d'algun error.

**Comment by carduque** [comment]
En el dashboard hi han 188 entrades comptabilitzades. Poder crear un event i mirar-ho.

feerbox::DATABASE=> select count(*) from counterpeople where reference='CP2017003' and time between '2018/02/19 11:49:00' and '2018/02/19 12:16:53';
 count
-------
   188
(1 fila)

**Comment by agrauHCB** [comment]
A veure, pensava que el problema que em va comentar el David es que l'hora del servidor no era la mateixa d'una app que ha fet servir ell per mesurar les persones.
Podem fer alguna cosa per sincrontizar la app amb l'hora de la raspi i amb l'hora del servidor?

**Comment by carduque** [comment]
This issue was moved to carduque/heroku#27
