### ISSUE TITLE
Càlcul del NPS és incorrecte

### ISSUE THREAD

**Issue by carduque** [carduque/FeerBoxClient#6]
S'ha de fer sobre els totals, no sobre els percentatges

**Comment by agrauHCB** [comment]
Llavors és correcte el valor de NPS que oferim o s'ha d'arreglar?

**Comment by carduque** [comment]
és calcula com % detractors - % de promotors
Jo diria que és correcte.

**Comment by agrauHCB** [comment]
Pero llavors no afecta el volum de vots?
Ho pregunto al alex

Thanks,

**Comment by carduque** [comment]
This issue was moved to carduque/heroku#7

**Comment by carduque** [comment]
This issue was moved to carduque/heroku#10
