### ISSUE TITLE
Alert de inactivitat

### ISSUE THREAD

**Issue by agrauHCB** [carduque/FeerBoxClient#8]
Fer alert (enviar e-mail) si un dispositiu porta més de 2hores sense enviar dades

**Comment by carduque** [comment]
Quines màquines tenim ara on poder probar aquesta alerta?

**Comment by agrauHCB** [comment]
Els dispositius que m'interessaria activar serien:
Inicialment comencem amb aquests
.Mercat de Barberà:
 CP2017040
 CP2017041
. Mercat Rubí
 CP2017025
 CP2017028

Solmania
 2017011
 2017009

Mercat Independència
 CP2017002
 CP2017003
 2017004

**Comment by carduque** [comment]
Activat a producció, a veure com va.
Totes les màquines d'abans a dia d'avui envien status correctament:

```
reference |      last_status_sent
-----------+-------------------------
 CP2017002 | 2018-02-14 22:20:43.5
 2017011   | 2018-02-14 22:25:38.374
 CP2017028 | 2018-02-14 22:31:19.307
 CP2017025 | 2018-02-14 22:31:19.619
 2017004   | 2018-02-14 22:33:41.609
 2017009   | 2018-02-14 22:34:13.633
 CP2017003 | 2018-02-14 22:40:14.996
 CP2017040 | 2018-02-14 21:53:19.332
 CP2017041 | 2018-02-14 21:56:37.321
```

**Comment by agrauHCB** [comment]
Ok, on s'envia el status?
Vull dir a quin e-mail?

**Comment by carduque** [comment]
support@happycustomerbox.com

que esta redireccionat a info@happycustomerbox.com

**Comment by agrauHCB** [comment]
Que a la vegada esta redirigit a agrau@happycustomerbox.com?

**Comment by carduque** [comment]
crec que si :-)

**Comment by agrauHCB** [comment]
Perfecte, pero m'ha confirmat del mercat de Barberà que tanquen la llum a les 22.00 fins a les 5 del matí, per tant hauriem d'ajustar el programa, per evitar que ens envii l'alarma cada nit.

**Comment by carduque** [comment]
És una merda que ho sapiguem ara.

**Comment by carduque** [comment]
He possat que les màquines de Barberà només envien alerta si Status not send in 7,5 hores

**Comment by agrauHCB** [comment]
Com a solució temporal ok,  però no com a definitiva.
No s'havia pensat que podien treure la llum a la nit :(

**Comment by agrauHCB** [comment]
Acabo de veure que pel cap de setmana, apaguen dissabte, fins dilluns no es torna o obrir.
No és greu, però hem de pensar-hi com ho podem solucionar.
El sistema d'alarmes és molt bona idea, i ens pot evitar molts pollos de producció

**Comment by carduque** [comment]
Quins dispositius necessiten alertes de botons?

**Comment by carduque** [comment]
This issue was moved to carduque/heroku#11
